=== dasch-swiss/dsp-api/webapi/src/main/resources/mappingXMLToStandoff.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 * Copyright Â© 2015-2018 the contributors (see Contributors.md).
 *
 * This file is part of Knora.
 *
 * Knora is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Knora is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with Knora.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- root element that contains all the elements of the mapping -->
    <xs:element name="mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="defaultXSLTransformation" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="mappingElement" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="tagname">
            <xs:selector xpath="mappingElement/tag"/>
            <xs:field xpath="name"/>
            <xs:field xpath="class"/>
            <xs:field xpath="namespace"/>
        </xs:unique>
        <xs:unique name="standoffClass">
            <xs:selector xpath="mappingElement/standoffClass"/>
            <xs:field xpath="classIri"/>
        </xs:unique>
    </xs:element>

    <!-- default XSL transformation to convert XML to HTML -->
    <xs:element name="defaultXSLTransformation">
        <xs:simpleType>
            <xs:restriction base="xs:anyURI">
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- an element mapping a tagname to a standoff class -->
    <xs:element name="mappingElement">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tag"/>
                <xs:element ref="standoffClass"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- represents a tagname including a namespace -->
    <!-- if no namespace is used, "noNamespace" has to be used -->
    <xs:element name="tag">
        <xs:complexType>
            <xs:sequence>
                <!-- name of the XML element -->
                <xs:element name="name">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- name of the class to be used in combination with the element -->
                <xs:element name="class">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- namespace of the XML element -->
                <xs:element name="namespace">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- indicates if an element requires a separator in the string when converted to standoff-->
                <xs:element name="separatesWords">
                    <xs:simpleType>
                        <xs:restriction base="xs:boolean"/>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- represents a standoff class optionally including attributes and a data type -->
    <xs:element name="standoffClass">
        <xs:complexType>
            <xs:sequence>
                <!-- IRI of the corresponding standoff class -->
                <xs:element name="classIri">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- maps XML attributes to standoff properties -->
                <xs:element ref="attributes" minOccurs="0"/>
                <!-- the data type of the standoff class (optional) -->
                <xs:element ref="datatype" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- contains all the attributes that may occur on this element -->
    <xs:element name="attributes">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="attribute"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="attribute">
            <xs:selector xpath="attribute"/>
            <xs:field xpath="attributeName"/>
            <xs:field xpath="namespace"/>
        </xs:unique>
        <xs:unique name="property">
            <xs:selector xpath="attribute"/>
            <xs:field xpath="propertyIri"/>
        </xs:unique>
    </xs:element>

    <!-- maps an attribute to a property -->
    <xs:element name="attribute">
        <xs:complexType >
            <xs:sequence>
                <!-- the name of the XML attribute -->
                <xs:element name="attributeName">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- the namespace of the XML attribute -->
                <!-- if no namespace is used, "noNamespace" has to be used -->
                <xs:element name="namespace">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- the IRI of the corresponding standoff property -->
                <xs:element name="propertyIri">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- represents a typed standoff class -->
    <xs:element name="datatype">
        <xs:complexType>
            <xs:sequence>
                <!-- the data type of standoff class -->
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <!-- the name of the XML attribute containing the representation of the data type value (e.g. a date string) -->
                <xs:element name="attributeName">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== dasch-swiss/dsp-api/webapi/_test_data/test_route/texts/mappingForHTML.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../src/main/resources/mappingXMLToStandoff.xsd">
    <mappingElement>
        <tag><name>text</name><class>noClass</class><namespace>noNamespace</namespace></tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffRootTag</classIri>
            <attributes>
                <attribute><attributeName>documentType</attributeName><namespace>noNamespace</namespace><propertyIri>http://www.knora.org/ontology/standoff#standoffRootTagHasDocumentType</propertyIri></attribute>
            </attributes>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>p</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffParagraphTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>em</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffItalicTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>strong</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffBoldTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>u</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace></tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffUnderlineTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>sub</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffSubscriptTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>sup</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffSuperscriptTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>strike</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffStrikethroughTag</classIri>
        </standoffClass>
    </mappingElement>

    <!-- a tag without class -> external link -->
    <mappingElement>
        <tag>
            <name>a</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffUriTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffUriTag</type>
                <attributeName>href</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- a tag with class "salsah-link" -> internal link -->
    <mappingElement>
        <tag>
            <name>a</name>
            <class>salsah-link</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffLinkTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffLinkTag</type>
                <attributeName>href</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "date" -> data type date -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>date</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffDateTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffDateTag</type>
                <attributeName>data-date</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "event" -> data type date -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>event</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/anything#StandoffEventTag</classIri>
            <attributes>
                <attribute><attributeName>data-description</attributeName><namespace>noNamespace</namespace><propertyIri>http://www.knora.org/ontology/anything#standoffEventTagHasDescription</propertyIri></attribute>
            </attributes>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffDateTag</type>
                <attributeName>data-date</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "interval" -> data type interval -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>interval</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffIntervalTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffIntervalTag</type>
                <attributeName>data-interval</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "color" -> data type color -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>color</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffColorTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffColorTag</type>
                <attributeName>data-color</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "integer" -> data type integer -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>integer</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffIntegerTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffIntegerTag</type>
                <attributeName>data-integer</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "decimal" -> data type decimal -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>decimal</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffDecimalTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffDecimalTag</type>
                <attributeName>data-decimal</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <!-- span tag with class "boolean" -> data type boolean -->
    <mappingElement>
        <tag>
            <name>span</name>
            <class>boolean</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffBooleanTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffBooleanTag</type>
                <attributeName>data-boolean</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

</mapping>

=== dasch-swiss/dsp-api/test_data/test_route/texts/freetestCustomMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../modules/webapi/src/main/resources/mappingXMLToStandoff.xsd">

    <mappingElement>
        <tag>
            <name>text</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffRootTag</classIri>
            <attributes>
                <attribute>
                    <attributeName>documentType</attributeName>
                    <namespace>noNamespace</namespace>
                    <propertyIri>http://www.knora.org/ontology/standoff#standoffRootTagHasDocumentType</propertyIri>
                </attribute>
            </attributes>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>section</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffParagraphTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>italic</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffItalicTag</classIri>
        </standoffClass>
    </mappingElement>

</mapping>

=== dasch-swiss/dsp-api/test_data/test_route/texts/mappingForLetterWithXSLTransformation.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../modules/webapi/src/main/resources/mappingXMLToStandoff.xsd">
    <defaultXSLTransformation>toBeDefined</defaultXSLTransformation>
    <mappingElement>
        <tag>
            <name>text</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffRootTag</classIri>
            <attributes>
                <attribute>
                    <attributeName>documentType</attributeName>
                    <namespace>noNamespace</namespace>
                    <propertyIri>http://www.knora.org/ontology/standoff#standoffRootTagHasDocumentType</propertyIri>
                </attribute>
            </attributes>
        </standoffClass>
    </mappingElement>
    
    <mappingElement>
        <tag>
            <name>p</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>true</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffParagraphTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>i</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffItalicTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>b</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffBoldTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>facsimile</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/0801/beol#StandoffFacsimileTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffLinkTag</type>
                <attributeName>src</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>math</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/0801/beol#StandoffMathTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>ref</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffInternalReferenceTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffInternalReferenceTag</type>
                <attributeName>href</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>sub</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffSubscriptTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>sup</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffSuperscriptTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>a</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
            <separatesWords>false</separatesWords>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffUriTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffUriTag</type>
                <attributeName>href</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

</mapping>

=== dasch-swiss/dsp-api/webapi/_test_data/test_route/texts/mappingForLetter.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="../../../src/main/resources/mappingXMLToStandoff.xsd">
    <mappingElement>
        <tag>
            <name>text</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffRootTag</classIri>
            <attributes>
                <attribute>
                    <attributeName>documentType</attributeName>
                    <namespace>noNamespace</namespace>
                    <propertyIri>http://www.knora.org/ontology/standoff#standoffRootTagHasDocumentType</propertyIri>
                </attribute>
            </attributes>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>p</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffParagraphTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>i</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffItalicTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>b</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffBoldTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>facsimile</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/beol#StandoffFacsimileTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffUriTag</type>
                <attributeName>src</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>math</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/beol#StandoffMathTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>ref</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/beol#StandoffReferenceTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>sub</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffSubscriptTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>sup</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/standoff#StandoffSuperscriptTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>nowiki</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/beol#StandoffNoWikiTag</classIri>
        </standoffClass>
    </mappingElement>

    <mappingElement>
        <tag>
            <name>a</name>
            <class>noClass</class>
            <namespace>noNamespace</namespace>
        </tag>
        <standoffClass>
            <classIri>http://www.knora.org/ontology/knora-base#StandoffUriTag</classIri>
            <datatype>
                <type>http://www.knora.org/ontology/knora-base#StandoffUriTag</type>
                <attributeName>href</attributeName>
            </datatype>
        </standoffClass>
    </mappingElement>

</mapping>
